---

- hosts: ansible-server
  become: true

  tasks:

    - name: load vars
      include_vars: '{{ item }}'
      with_items:
        - releases/{{ Release }}/all.yml

    - name: copy Dockerfile
      copy:
        src: Dockerfile
        dest: /root/Dockerfile

    - name: create app dir
      file:
        path: /root/app
        state: directory

    - name: generate jinja2 app/app.py
      template:
        src: releases/{{ Release }}/app.py.j2
        dest: /root/app/app.py

    - name: copy requirements.txt
      copy:
        src: releases/{{ Release }}/requirements.txt
        dest: /root/requirements.txt

    - name: remove a container
      docker_container:
        name: flaskapp-{{ version }}
        state: absent

    - name: create docker image
      shell: docker build -t docker-flask:latest .
      register: docker_image_list_output

    - name: docker image list
      debug:
        msg: '{{ docker_image_list_output.stdout_lines }}'

    - name: run docker with the app
      shell: docker run --name flaskapp-{{ version }} -d -v $PWD/app:/app -p 5000:5000 docker-flask:latest
      register: docker_list_output

    - name: docker list
      debug:
        msg: '{{ docker_list_output.stdout_lines }}'