- hosts: ansible-server
  become: true

  tasks:

    - name: copy Dockerfile
      copy:
        src: Dockerfile
        dest: /root/Dockerfile

    - name: create docker image using Dockerfile
      command: docker stop flaskapp;docker rm flaskapp

    - name: create docker image using Dockerfile
      command: docker build -t docker-flask:latest .

    - name: run docker with the app
      command: docker run --name flaskapp -d -v $PWD/app:/app -p 5000:5000 docker-flask:latest

