# A scrape configuration scraping a Node Exporter and the Prometheus server
# itself.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
    - targets: ['ec2-18-195-150-173.eu-central-1.compute.amazonaws.com:9100']
  - job_name: 'container'
    scrape_interval: 5s
    static_configs:
    - targets: ['ec2-18-195-150-173.eu-central-1.compute.amazonaws.com:9104']